Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Choose a search to run
query = '"cute cat"'

#Run the search and request some additional info
tweets_info = client.search_recent_tweets(query=query, tweet_fields=["author_id", "created_at", "id", "lang", "public_metrics", "source", "text"])

# Get the actual list of tweets out of the data field (tweets_info also has metadata about our search)
tweets_list = tweets_info.data
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Input [1;32mIn [10][0m, in [0;36m<cell line: 8>[1;34m()[0m
[0;32m      5[0m tweets_info [38;5;241m=[39m client[38;5;241m.[39msearch_recent_tweets(query[38;5;241m=[39mquery, tweet_fields[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mauthor_id[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcreated_at[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mid[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mlang[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mpublic_metrics[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124msource[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mtext[39m[38;5;124m"[39m])
[0;32m      7[0m [38;5;66;03m# Get the actual list of tweets out of the data field (tweets_info also has metadata about our search)[39;00m
[1;32m----> 8[0m tweets_list [38;5;241m=[39m [43mtweets_info[49m[38;5;241;43m.[39;49m[43mdata[49m

[1;31mAttributeError[0m: 'NoneType' object has no attribute 'data'
AttributeError: 'NoneType' object has no attribute 'data'

