Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
userInfo = client.get_user(username="KSeattleWeather")
display(userInfo)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUnauthorized[0m                              Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m userInfo [38;5;241m=[39m [43mclient[49m[38;5;241;43m.[39;49m[43mget_user[49m[43m([49m[43musername[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mKSeattleWeather[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      2[0m display(userInfo)

File [1;32mC:\Python310\lib\site-packages\tweepy\client.py:2423[0m, in [0;36mClient.get_user[1;34m(self, id, username, user_auth, **params)[0m
[0;32m   2420[0m [38;5;28;01melse[39;00m:
[0;32m   2421[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mID or username is required[39m[38;5;124m"[39m)
[1;32m-> 2423[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_make_request[49m[43m([49m
[0;32m   2424[0m [43m    [49m[38;5;124;43m"[39;49m[38;5;124;43mGET[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mroute[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mparams[49m[43m,[49m
[0;32m   2425[0m [43m    [49m[43mendpoint_parameters[49m[38;5;241;43m=[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mexpansions[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mtweet.fields[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43muser.fields[39;49m[38;5;124;43m"[39;49m[43m)[49m[43m,[49m
[0;32m   2426[0m [43m    [49m[43mdata_type[49m[38;5;241;43m=[39;49m[43mUser[49m[43m,[49m[43m [49m[43muser_auth[49m[38;5;241;43m=[39;49m[43muser_auth[49m
[0;32m   2427[0m [43m[49m[43m)[49m

File [1;32mC:\Python310\lib\site-packages\tweepy\client.py:126[0m, in [0;36mBaseClient._make_request[1;34m(self, method, route, params, endpoint_parameters, json, data_type, user_auth)[0m
[0;32m    122[0m [38;5;28;01mdef[39;00m [38;5;21m_make_request[39m([38;5;28mself[39m, method, route, params[38;5;241m=[39m{}, endpoint_parameters[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m    123[0m                   json[38;5;241m=[39m[38;5;28;01mNone[39;00m, data_type[38;5;241m=[39m[38;5;28;01mNone[39;00m, user_auth[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[0;32m    124[0m     request_params [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_process_params(params, endpoint_parameters)
[1;32m--> 126[0m     response [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mrequest[49m[43m([49m[43mmethod[49m[43m,[49m[43m [49m[43mroute[49m[43m,[49m[43m [49m[43mparams[49m[38;5;241;43m=[39;49m[43mrequest_params[49m[43m,[49m
[0;32m    127[0m [43m                            [49m[43mjson[49m[38;5;241;43m=[39;49m[43mjson[49m[43m,[49m[43m [49m[43muser_auth[49m[38;5;241;43m=[39;49m[43muser_auth[49m[43m)[49m
[0;32m    129[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mreturn_type [38;5;129;01mis[39;00m requests[38;5;241m.[39mResponse:
[0;32m    130[0m         [38;5;28;01mreturn[39;00m response

File [1;32mC:\Python310\lib\site-packages\tweepy\client.py:97[0m, in [0;36mBaseClient.request[1;34m(self, method, route, params, json, user_auth)[0m
[0;32m     95[0m     [38;5;28;01mraise[39;00m BadRequest(response)
[0;32m     96[0m [38;5;28;01mif[39;00m response[38;5;241m.[39mstatus_code [38;5;241m==[39m [38;5;241m401[39m:
[1;32m---> 97[0m     [38;5;28;01mraise[39;00m Unauthorized(response)
[0;32m     98[0m [38;5;28;01mif[39;00m response[38;5;241m.[39mstatus_code [38;5;241m==[39m [38;5;241m403[39m:
[0;32m     99[0m     [38;5;28;01mraise[39;00m Forbidden(response)

[1;31mUnauthorized[0m: 401 Unauthorized
Unauthorized
Unauthorized: 401 Unauthorized
Unauthorized

